/**
 * Builds the AI assistant knowledge base from the user-guide HTML files.
 *
 * Strips each curated guide in `planning/user-guides/` down to readable text and
 * writes a single committed module (`src/lib/ai/guide-kb.generated.ts`) that the
 * admin assistant feeds to Gemini as grounding context.
 *
 * Re-run whenever the guides change:  npm run build:guide-kb
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const GUIDES_DIR = join(process.cwd(), 'planning', 'user-guides');
const OUT_FILE = join(process.cwd(), 'src', 'lib', 'ai', 'guide-kb.generated.ts');

// Skip files that are noise for a text Q&A KB: the design-mockup gallery (mostly
// markup), the table-of-contents page, dev-only duplicates, and non-HTML assets.
// generating-users.html and phase-1-auth.html are "this page moved" redirect stubs.
const SKIP = new Set([
  'app-designs.html',
  'index.html',
  'generating-users.html',
  'phase-1-auth.html',
]);
const skipFile = (name: string) =>
  !name.endsWith('.html') || name.endsWith('.DEV.html') || SKIP.has(name);

const ENTITIES: Record<string, string> = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&#39;': "'",
  '&apos;': "'",
  '&nbsp;': ' ',
  '&rarr;': '→',
  '&mdash;': '—',
  '&ndash;': '–',
  '&hellip;': '…',
  '&checkmark;': '✓',
};

function stripHtml(html: string): string {
  let text = html;
  // Drop non-content blocks entirely.
  text = text.replace(/<style[\s\S]*?<\/style>/gi, '');
  text = text.replace(/<script[\s\S]*?<\/script>/gi, '');
  text = text.replace(/<head[\s\S]*?<\/head>/gi, '');
  text = text.replace(/<!--[\s\S]*?-->/g, '');
  // Turn block-level boundaries into newlines so structure survives.
  text = text.replace(/<\/(p|div|section|article|li|h[1-6]|tr|table|ul|ol|header)>/gi, '\n');
  text = text.replace(/<(br|hr)\s*\/?>/gi, '\n');
  text = text.replace(/<li[^>]*>/gi, '\n• ');
  text = text.replace(/<h[1-6][^>]*>/gi, '\n\n');
  // Strip all remaining tags.
  text = text.replace(/<[^>]+>/g, ' ');
  // Decode entities.
  text = text.replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)));
  for (const [ent, ch] of Object.entries(ENTITIES)) {
    text = text.split(ent).join(ch);
  }
  // Collapse whitespace.
  text = text.replace(/[ \t]+/g, ' ');
  text = text.replace(/ *\n */g, '\n');
  text = text.replace(/\n{3,}/g, '\n\n');
  return text.trim();
}

function decodeEntities(s: string): string {
  let out = s.replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)));
  for (const [ent, ch] of Object.entries(ENTITIES)) out = out.split(ent).join(ch);
  return out;
}

function titleOf(html: string, fallback: string): string {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  if (m) return decodeEntities(m[1].replace(/\s+/g, ' ').trim());
  return fallback;
}

function main() {
  const files = readdirSync(GUIDES_DIR)
    .filter((f) => !skipFile(f))
    .sort();

  const sections: string[] = [];
  const sources: string[] = [];

  for (const file of files) {
    const raw = readFileSync(join(GUIDES_DIR, file), 'utf8');
    const body = stripHtml(raw);
    if (body.length < 40) continue; // skip near-empty stubs
    const title = titleOf(raw, file);
    sources.push(title);
    sections.push(`### GUIDE: ${title} (${file})\n\n${body}`);
  }

  const kb = sections.join('\n\n---\n\n');

  const out = `/* eslint-disable */
// AUTO-GENERATED by scripts/build-guide-kb.ts — DO NOT EDIT BY HAND.
// Re-run \`npm run build:guide-kb\` after editing files in planning/user-guides/.
// Source guides: ${sources.length} files.

export const GUIDE_KB_SOURCES: string[] = ${JSON.stringify(sources, null, 2)};

export const GUIDE_KB = ${JSON.stringify(kb)};
`;

  writeFileSync(OUT_FILE, out, 'utf8');
  console.log(
    `✓ Wrote ${OUT_FILE}\n  ${sources.length} guides, ${kb.length.toLocaleString()} chars (~${Math.round(
      kb.length / 4,
    ).toLocaleString()} tokens)`,
  );
  for (const s of sources) console.log(`    • ${s}`);
}

main();
